### Read all films with File variable
@baseUrl = http://localhost:3000
GET {{baseUrl}}/films

### Read all films filtered by minimum-duration
GET {{baseUrl}}/films?minimum-duration=150

### Read a film with his id
GET {{baseUrl}}/films/3

### Create a film
POST {{baseUrl}}/films
Content-Type: application/json

{
    "title":"Dragon Ball Z: 100 plus tard",
    "duration":160,
    "budget": 12000000,
    "link":"https://ibrahim-ayachi-vinci.github.io/covidClicker/"
}

### Read all films filtered by charDebut
GET {{baseUrl}}/films?charDebut=Drag

### Read all films sorted by title (ascending)
GET {{baseUrl}}/films/?order=+title

### Read all films sorted by title (descending)
GET {{baseUrl}}/films/?order=-title

### Delete film identified by 2
DELETE {{baseUrl}}/films/3

### Update the film identified by 1
PATCH {{baseUrl}}/films/1
Content-Type: application/json

{
    "title":"Dragon Ball Z: Les mercenaires de l'espace"
}

### Update the pizza identified by 6
PUT {{baseUrl}}/pizzas/9
Content-Type: application/json

{
    "title":"Dragon Ball Z: picollo daimao",
    "duration":160,
    "budget": 12000000,
    "link":"https://ibrahim-ayachi-vinci.github.io/covidClicker/"
}

